### ISSUE TITLE
preprocessing problem

### ISSUE THREAD

**Issue by FunnelChao** [Wenlab/CeNDeR#1]
the link of ‘data/benchmarks/fDNC/preprocessing/’ in osf seems broken，could you please provide the new link or preprocessing scripts

**Comment by wuyxiquanquan** [comment]
You can access the folder through the Google Drive: https://drive.google.com/drive/folders/1tdS3AFJUQ_KHWqe5AvgBTfttN7TuaVzL?usp=sharing
